source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Better_Errors
gem "better_errors"

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# PostgreSQL
gem 'pg'

# Annotate
gem 'annotate'

# Bootstrap
gem 'twitter-bootstrap-rails'

# Devise
gem 'devise'
gem 'devise-bootstrap-views'

# CanCan
gem 'cancan'

# Base de datos
gem 'mysql2'

# Para verificar rut
gem 'rut_validation'

# Para el crawler
gem 'rest-client'

# Para los charts
gem 'chartkick'

# Para ordenar por dias al usar charts
gem 'groupdate'

# Gema para profile image
gem 'paperclip'

# Gema para autocomplete
gem 'rails4-autocomplete'
gem 'jquery-ui-rails'
gem 'angularjs-rails'
gem 'angular_rails_csrf'

# Paginar contenidos
gem 'will_paginate', '~> 3.0.6'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

